<b> Importing necessary libraries </b>

In [1]:
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
from sklearn import datasets
import pickle
from sklearn.decomposition import PCA
from __future__ import print_function
import keras
from keras.datasets import cifar10
import numpy as np


Using TensorFlow backend.


In [2]:
(x_train,y_train),(x_test,y_test)=cifar10.load_data()
x_train = x_train.astype('float32')
x_test = x_test.astype('float32')
print(x_train)
print(x_test)
print(y_train)

[[[[  59.   62.   63.]
   [  43.   46.   45.]
   [  50.   48.   43.]
   ..., 
   [ 158.  132.  108.]
   [ 152.  125.  102.]
   [ 148.  124.  103.]]

  [[  16.   20.   20.]
   [   0.    0.    0.]
   [  18.    8.    0.]
   ..., 
   [ 123.   88.   55.]
   [ 119.   83.   50.]
   [ 122.   87.   57.]]

  [[  25.   24.   21.]
   [  16.    7.    0.]
   [  49.   27.    8.]
   ..., 
   [ 118.   84.   50.]
   [ 120.   84.   50.]
   [ 109.   73.   42.]]

  ..., 
  [[ 208.  170.   96.]
   [ 201.  153.   34.]
   [ 198.  161.   26.]
   ..., 
   [ 160.  133.   70.]
   [  56.   31.    7.]
   [  53.   34.   20.]]

  [[ 180.  139.   96.]
   [ 173.  123.   42.]
   [ 186.  144.   30.]
   ..., 
   [ 184.  148.   94.]
   [  97.   62.   34.]
   [  83.   53.   34.]]

  [[ 177.  144.  116.]
   [ 168.  129.   94.]
   [ 179.  142.   87.]
   ..., 
   [ 216.  184.  140.]
   [ 151.  118.   84.]
   [ 123.   92.   72.]]]


 [[[ 154.  177.  187.]
   [ 126.  137.  136.]
   [ 105.  104.   95.]
   ..., 
   [  91.   95.   

<b> Applying PCA to reduce dimensions and selecting the top 200 variance components </b>

In [4]:
pca = PCA(n_components=200)
X_pca=pca.fit_transform(X)
X1_pca=pca.transform(X1)
print(X_pca.shape)


(50000, 200)


<b> Resizing the image matrix so as to get processed by inbuilt sklearn models </b>

In [3]:
X=x_train.reshape(50000,3*32*32)
X1=x_test.reshape(10000,3*32*32)
print(X)
Y=y_train.flatten()
Y1=y_test.flatten()
print(Y)

[[  59.   62.   63. ...,  123.   92.   72.]
 [ 154.  177.  187. ...,  143.  133.  144.]
 [ 255.  255.  255. ...,   80.   86.   84.]
 ..., 
 [  35.  178.  235. ...,   12.   31.   50.]
 [ 189.  211.  240. ...,  195.  190.  171.]
 [ 229.  229.  239. ...,  163.  163.  161.]]
[6 9 9 ..., 9 1 1]


<b> Applying svm on dataset </b>

In [5]:
from sklearn import svm
model = svm.SVC()
model.fit(X_pca,Y)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False)

In [7]:
X_predict=model.predict(X1_pca)

In [8]:
for i in X_predict:
 print(i)

9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9


9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9
9


In [9]:
print(X1_pca.shape)

(10000, 200)


<b> Applying random forest classifier on data set </b>

In [11]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier(n_estimators=1024, verbose=True)
rfc.fit(X_pca,Y)


[Parallel(n_jobs=1)]: Done 1024 out of 1024 | elapsed: 12.8min finished


RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=1024, n_jobs=1,
            oob_score=False, random_state=None, verbose=True,
            warm_start=False)

In [12]:
X_predict = rfc.predict(X1_pca)

[Parallel(n_jobs=1)]: Done 1024 out of 1024 | elapsed:    3.7s finished


In [13]:
for i in X_predict:
 print(i)

1
1
8
0
6
6
1
6
5
1
0
9
1
1
9
5
5
7
8
6
7
0
0
1
4
6
5
7
1
6
6
4
4
6
9
7
6
9
9
5
4
6
3
3
8
9
3
3
4
4
9
8
6
9
8
8
5
8
3
4
7
3
1
9
6
2
1
0
5
9
2
7
8
8
0
6
9
5
3
8
8
1
1
0
0
7
3
8
8
8
0
4
8
6
4
3
6
0
0
7
4
4
5
3
1
1
3
6
1
5
6
0
2
4
9
7
0
9
4
5
8
4
1
7
0
2
8
5
3
0
4
1
9
9
1
2
9
0
2
8
4
1
6
5
8
2
6
5
5
5
9
9
6
0
0
5
2
9
3
4
0
1
1
4
9
7
8
6
7
9
1
7
0
8
9
9
0
7
3
9
0
7
6
2
7
8
6
3
7
8
8
3
1
1
7
4
9
0
5
8
7
8
0
7
1
5
8
4
7
8
4
1
3
7
9
5
1
9
0
2
7
6
1
6
9
9
9
2
3
7
3
1
1
1
8
0
4
9
5
1
1
2
7
9
0
5
4
8
2
1
7
5
6
6
2
0
3
9
8
1
8
9
3
1
0
8
3
4
7
0
4
1
6
5
8
3
9
2
2
5
9
4
2
1
8
9
1
8
7
9
1
2
6
1
5
4
4
0
0
6
6
6
3
5
6
8
8
2
1
4
8
6
0
0
3
0
5
7
7
5
5
5
4
4
6
9
4
6
1
6
1
9
6
6
6
9
3
8
0
9
4
5
0
5
8
5
7
6
8
9
9
1
8
2
6
3
6
3
1
8
9
5
8
0
9
9
7
1
0
1
2
7
9
2
2
7
8
6
8
6
6
9
0
9
6
0
7
4
7
5
1
0
6
5
9
6
2
3
8
1
9
1
7
8
9
4
0
7
8
2
9
0
3
6
9
9
6
1
1
7
4
7
8
3
2
8
5
4
9
6
3
5
3
9
7
7
3
4
3
1
9
2
9
9
5
6
8
0
2
0
7
9
7
0
9
2
4
6
6
8
2
6
1
6
3
4
6
3
7
7
5
3
8
2
3
3
4
0
2
2
9
6
8
3
5
8
9
9
8
0
1
9
8
1
8
8
8
2
4
0


9
0
2
2
9
7
0
9
9
8
9
3
7
3
2
9
4
7
9
6
6
7
0
8
9
0
0
1
5
2
0
4
3
9
1
8
3
8
2
2
1
1
2
3
9
4
6
8
8
8
1
5
1
5
9
0
1
0
4
8
6
9
7
8
9
4
9
5
1
3
4
6
4
9
3
9
8
7
3
0
8
4
5
0
5
8
6
7
4
0
0
7
5
6
5
5
7
2
4
8
9
7
3
5
9
6
0
6
6
1
0
4
8
5
5
4
2
2
7
9
2
6
6
4
9
5
0
5
6
0
8
2
2
4
7
9
3
1
6
6
3
1
5
8
7
4
5
1
5
1
6
4
4
0
8
5
6
9
1
9
2
7
0
8
8
5
0
6
9
9
0
9
0
4
0
0
4
6
5
3
2
9
6
1
9
9
0
9
0
8
7
2
7
7
1
4
0
3
7
0
5
5
1
6
4
9
0
3
6
3
8
8
3
6
8
0
9
8
0
0
2
7
7
7
7
4
7
5
6
8
4
0
8
6
8
2
7
6
5
7
1
6
9
2
8
9
1
1
5
1
6
5
6
2
5
5
1
3
7
5
5
0
8
8
6
1
6
9
3
6
9
2
7
1
9
4
8
9
1
8
0
6
4
4
7
1
0
8
7
4
4
4
0
2
1
2
0
5
7
0
3
5
8
9
8
0
6
4
9
5
8
6
3
1
2
8
7
8
0
3
4
1
7
6
4
2
2
6
5
4
0
8
9
0
3
3
8
8
9
6
0
9
8
5
0
5
9
4
0
0
5
6
8
9
1
6
9
8
9
5
9
3
8
4
7
4
6
3
0
7
6
6
4
6
5
3
0
1
1
9
6
7
2
5
2
7
6
4
4
4
1
6
0
9
1
5
5
2
6
6
7
9
7
3
7
8
5
7
8
1
7
5
8
0
2
2
0
0
1
4
9
3
7
1
8
9
6
4
6
1
8
6
5
9
6
4
3
1
8
5
4
5
0
5
1
3
6
9
8
1
4
0
5
1
6
3
0
2
9
3
5
2
8
2
3
9
2
6
7
0
9
6
5
0
6
1
5
4
9
8
3
3
7
9
8
5
0
9
7
2
4
0
4
6
2
2
5
0
7
3


In [15]:
acc_train = metrics.accuracy_score(Y1, X_predict)
print(acc_train)

0.4941


In [17]:
dict1=dict()
dict1={0:'airplane',1:'automobile',2:'bird',3:'cat',4:'deer',5:'dog',6:'frog',7:'horse',8:'ship',9:'truck'}

<b> Getting the predicted values </b>

In [19]:
Y_predict=[]
for i in range(len(X_predict)):
 Y_predict.append(dict1[X_predict[i]])

In [20]:
for i in Y_predict:
    print(i)

automobile
automobile
ship
airplane
frog
frog
automobile
frog
dog
automobile
airplane
truck
automobile
automobile
truck
dog
dog
horse
ship
frog
horse
airplane
airplane
automobile
deer
frog
dog
horse
automobile
frog
frog
deer
deer
frog
truck
horse
frog
truck
truck
dog
deer
frog
cat
cat
ship
truck
cat
cat
deer
deer
truck
ship
frog
truck
ship
ship
dog
ship
cat
deer
horse
cat
automobile
truck
frog
bird
automobile
airplane
dog
truck
bird
horse
ship
ship
airplane
frog
truck
dog
cat
ship
ship
automobile
automobile
airplane
airplane
horse
cat
ship
ship
ship
airplane
deer
ship
frog
deer
cat
frog
airplane
airplane
horse
deer
deer
dog
cat
automobile
automobile
cat
frog
automobile
dog
frog
airplane
bird
deer
truck
horse
airplane
truck
deer
dog
ship
deer
automobile
horse
airplane
bird
ship
dog
cat
airplane
deer
automobile
truck
truck
automobile
bird
truck
airplane
bird
ship
deer
automobile
frog
dog
ship
bird
frog
dog
dog
dog
truck
truck
frog
airplane
airplane
dog
bird
truck
cat
deer
airplane
automo

deer
cat
cat
frog
horse
frog
truck
truck
frog
frog
horse
deer
deer
automobile
automobile
deer
truck
deer
automobile
ship
deer
frog
automobile
frog
cat
ship
dog
deer
cat
horse
truck
automobile
airplane
ship
bird
horse
dog
automobile
truck
ship
horse
airplane
truck
truck
automobile
horse
deer
dog
truck
deer
dog
frog
dog
horse
deer
truck
truck
deer
deer
automobile
cat
airplane
automobile
truck
horse
dog
truck
cat
automobile
frog
dog
dog
horse
deer
frog
deer
dog
deer
frog
frog
automobile
cat
airplane
deer
truck
cat
ship
airplane
bird
cat
deer
deer
dog
horse
bird
frog
ship
truck
frog
dog
deer
deer
truck
truck
dog
cat
airplane
deer
automobile
horse
cat
frog
frog
dog
dog
truck
frog
airplane
airplane
ship
frog
automobile
automobile
truck
ship
ship
airplane
frog
airplane
deer
automobile
frog
bird
frog
dog
truck
truck
cat
dog
cat
cat
airplane
ship
frog
dog
ship
cat
frog
frog
dog
bird
truck
cat
airplane
deer
truck
truck
bird
airplane
truck
automobile
deer
airplane
dog
dog
automobile
deer
bird
shi

deer
truck
deer
horse
cat
bird
airplane
dog
airplane
frog
horse
airplane
automobile
dog
ship
deer
horse
airplane
ship
deer
dog
frog
horse
truck
automobile
horse
truck
truck
airplane
automobile
automobile
automobile
airplane
frog
truck
truck
dog
frog
automobile
dog
truck
horse
truck
deer
dog
deer
truck
truck
truck
ship
bird
cat
deer
ship
truck
airplane
airplane
horse
dog
cat
ship
truck
bird
airplane
truck
bird
cat
frog
bird
cat
frog
dog
deer
bird
ship
airplane
frog
frog
dog
frog
frog
cat
airplane
dog
truck
bird
cat
dog
ship
airplane
dog
dog
deer
bird
truck
frog
airplane
cat
frog
airplane
horse
automobile
airplane
bird
deer
ship
bird
airplane
automobile
ship
frog
deer
ship
deer
bird
airplane
deer
ship
automobile
truck
cat
ship
dog
deer
cat
bird
dog
ship
cat
ship
truck
deer
dog
cat
deer
frog
horse
frog
bird
cat
automobile
bird
airplane
deer
truck
bird
automobile
frog
frog
deer
automobile
ship
dog
deer
dog
truck
ship
dog
frog
horse
automobile
horse
cat
frog
automobile
airplane
horse
truck


deer
deer
automobile
dog
dog
automobile
dog
dog
frog
frog
dog
bird
ship
cat
airplane
truck
ship
automobile
dog
automobile
dog
ship
frog
airplane
deer
cat
bird
dog
frog
cat
ship
truck
dog
frog
airplane
bird
dog
airplane
frog
horse
bird
ship
truck
deer
horse
truck
horse
ship
ship
truck
automobile
automobile
dog
airplane
airplane
truck
horse
cat
horse
deer
frog
bird
cat
cat
bird
deer
frog
frog
airplane
truck
cat
truck
ship
dog
horse
ship
truck
deer
ship
automobile
airplane
automobile
truck
horse
frog
horse
horse
dog
deer
truck
cat
truck
ship
deer
horse
automobile
frog
horse
cat
truck
horse
dog
dog
truck
automobile
truck
bird
airplane
truck
cat
truck
ship
ship
frog
horse
dog
horse
automobile
truck
truck
ship
truck
cat
frog
bird
ship
dog
dog
airplane
cat
truck
horse
frog
dog
cat
cat
automobile
ship
ship
automobile
frog
cat
truck
airplane
airplane
deer
ship
truck
deer
automobile
horse
ship
airplane
automobile
cat
truck
horse
ship
horse
airplane
horse
dog
bird
ship
horse
horse
frog
dog
dog
bi

In [21]:
np.savetxt("cifar10.csv",Y_predict,fmt="%s")